version: 1.0.0.{build}
branches:
  only:
  - master
skip_tags: true
build_script:
- ps: >-
    $env:VERSION=$env:APPVEYOR_BUILD_VERSION

    .\build.ps1 Package
test_script:
- ps: >-
    .\build.ps1 UnitTest

    $build_success = $?


    # upload results to AppVeyor

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\Test.xml))


    if (-not $build_success) {
      exit 1
    }
artifacts:
- path: Output\Packages\*.nupkg
  name: Chocolatey Package
deploy:
- provider: NuGet
  server: http://chocolatey.org/
  api_key:
    secure: +zfBtvqI0yIQodWvYBH7F0q8Mgjvlk4jswvEowSayB9LR4KaD36mkoEJHvRbY1TX
  skip_symbols: true
- provider: NuGet
  api_key:
    secure: CX9G8eA/ROI4KCfHIl1cG0gLMaTI51+6PIFoYLNSsuVKCPUulCSL5xerxIqqSaw/
  skip_symbols: true
